# 1. Numpy package

## 1.1 numpy array basics

In [1]:
import numpy as np

In [2]:
l  = list(range(1,11))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
my_array = np.array(l) #transform array to numpy array (ndarray)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
type(my_array)

numpy.ndarray

In [8]:
for i in my_array:    # can be iterated like lists
    print(i)


1
2
3
4
5
6
7
8
9
10


### in arrays, all elements must have same data types unlike lists.

In [9]:
l = [1,2.5,"Dog", True]
l

[1, 2.5, 'Dog', True]

In [11]:
new_array = np.array(l)
print(new_array)   #all are converted to string

['1' '2.5' 'Dog' 'True']


In [13]:
for i in new_array:  #checking the type, which is string
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [20]:
b = np.array([1.,2,"3"])
b

array(['1.0', '2', '3'], dtype='<U32')

In [21]:
type(b)

numpy.ndarray

In [22]:
b.dtype #can check single datatype of all elements

dtype('<U32')

## 1.2 numpy array( element wise operations / vectorisation)

In [23]:
import numpy as np

In [25]:
np.arange(1,11) #create ndarray from 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,11,2) #every second no. from 1 to 10

array([1, 3, 5, 7, 9])

### differences b/w lists and ndarrays

In [29]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [30]:
l*2  #not an element wise operation

[1, 2, 3, 4, 1, 2, 3, 4]

In [32]:
l1 = []  #element wise operation requires alot of code
for i in l:
    l1.append(i*2)
l1

[2, 4, 6, 8]

In [33]:
l+2 #not an element wise operation and doesn't work at all :(

TypeError: can only concatenate list (not "int") to list

In [34]:
a = np.arange(1,5) #create ndarray with elements as 1-4
a

array([1, 2, 3, 4])

In [37]:
print(a*2, a+2, a/2, a-2, a**2, 2**a, sep = "\n")  #element wise operations are possible and easy

[2 4 6 8]
[3 4 5 6]
[0.5 1.  1.5 2. ]
[-1  0  1  2]
[ 1  4  9 16]
[ 2  4  8 16]


In [39]:
np.sqrt(a)  #srqt of all elements

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [40]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [41]:
np.sum(a)

10

In [45]:
a.sum()

10

In [46]:
sum(a)

10

In [48]:
a.size #no. of elements in ndarray

4

In [49]:
len(a)  #same as size

4

In [52]:
a[1] = 34.5

In [54]:
np.abs(a) #absolute values of all elements

array([ 1, 34,  3,  4])

In [56]:
np.ceil(a) #rounding up element wise

array([ 1., 34.,  3.,  4.])

In [57]:
l  = [1.2,3,4]

In [58]:
list.ceil(l)

AttributeError: type object 'list' has no attribute 'ceil'

In [68]:
np.around(([2.33]), decimals = 1)  # rounds to given decimal points

array([2.3])

## 1.3 numpy array (indexing and slicing)

In [69]:
import numpy as np

In [70]:
a = np.arange(1,11)  #array from 1 to 10 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
a[0]

1

In [72]:
a[-1]

10

In [73]:
list(enumerate(a))

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [74]:
a[2:6]

array([3, 4, 5, 6])

In [75]:
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a[:5]

array([1, 2, 3, 4, 5])

In [77]:
a[::2]

array([1, 3, 5, 7, 9])

In [78]:
a[::3]

array([ 1,  4,  7, 10])

In [80]:
a[0] = 100 #assignment using index value
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [82]:
a[2:5] = 50 #broadcasting
a

array([100,   2,  50,  50,  50,   6,   7,   8,   9,  10])

In [86]:
a[2:5] = [34,56,78] #this is also possible
a

array([100,   2,  34,  56,  78,   6,   7,   8,   9,  10])

In [87]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
b = a[2:8] #slicing a and assigning it to b
b

array([3, 4, 5, 6, 7, 8])

In [92]:
b[0] = 100 #changing value in b reflects in a as well
b

array([100,   4,   5,   6,   7,   8])

In [94]:
a  #respective element is changed in a as well (referecncing)

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

### making another array from sliced array references to the original while in lists it ref. to a copy

----------------------------------------------------------

## 1.4 numpy array (shape and multiple dimensions

In [1]:
import numpy as np

In [2]:
a = np.arange(1,13)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape   #1-D array, 12 elements in one dimension (vector)

(12,)

In [8]:
a = a.reshape(2,6)  #reshaping a, 2 rows and 6 columns

In [9]:
a  

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
a.shape

(2, 6)

In [15]:
a = a.reshape(6,2) #reshaping to 6 rows and 2 columns
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [16]:
a.shape

(6, 2)

In [19]:
a+100  #elemnent wise op still works

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 110],
       [111, 112]])

In [18]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [20]:
a.reshape(3,5) #wont work as it has only 12 elements

ValueError: cannot reshape array of size 12 into shape (3,5)

In [23]:
a= a.reshape(2,2,3)  #creating a 3-D array
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
a.shape

(2, 2, 3)

In [26]:
b = np.arange(1,101).reshape(25,4)  # create 2-D array with one line of code
b

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

## 1.5 numpy arrays ( slicing and indexing of M-D arrays)

In [27]:
import numpy as np

In [62]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [63]:
a = a.reshape(3,4)  #( order= "F" ) is for changing order in 2-D array
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
a[0]  #first row

array([1, 2, 3, 4])

In [65]:
a[-1]

array([ 9, 10, 11, 12])

In [66]:
a[0][0] #can also be used as a[0,0]

1

In [67]:
a[0,0]

1

In [69]:
a[:,0] #all rows, first column

array([1, 5, 9])

In [48]:
print(a[:2, 1:3]) #first 2 rows, column 1 and 3

[[2 3]
 [6 7]]


In [70]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
a[:,-1]

array([ 4,  8, 12])

In [50]:
a.T  #transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
a.transpose() #same

array([[ 0,  1,  9],
       [ 0,  1, 10],
       [ 0,  1, 11],
       [ 1,  2, 12]])

In [75]:
a[:,-1] = a[:,-1]/4 #changing slice inplace

In [74]:
a

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  2],
       [ 9, 10, 11,  3]])

In [76]:
a = np.arange(1,13).reshape(3,4)

In [77]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
a.sum() #sum of all elements

78

In [80]:
sum(a) #sums all columns

array([15, 18, 21, 24])

In [81]:
a.sum(axis = 0) #sum of each column

array([15, 18, 21, 24])

In [82]:
a.sum(axis = 1) #sum of each row

array([10, 26, 42])

In [84]:
a.cumsum() #cumulative sum of each element

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78], dtype=int32)

In [85]:
a.cumsum(axis = 0) #cumsum of each column

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]], dtype=int32)

In [86]:
a.cumsum(axis = 1) #cumsum of each row

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]], dtype=int32)

In [87]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
a.prod() #product of all elemnets

479001600

In [91]:
a.prod( axis = 0) #p of all col elements

array([ 45, 120, 231, 384])

In [92]:
a.prod(axis = 1) #prod of all row elements

array([   24,  1680, 11880])

## 1.6 boolean indexing