# 1. Numpy package

## 1.1 numpy array basics

In [1]:
import numpy as np

In [2]:
l  = list(range(1,11))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
my_array = np.array(l) #transform array to numpy array (ndarray)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
type(my_array)

numpy.ndarray

In [8]:
for i in my_array:    # can be iterated like lists
    print(i)


1
2
3
4
5
6
7
8
9
10


### in arrays, all elements must have same data types unlike lists.

In [9]:
l = [1,2.5,"Dog", True]
l

[1, 2.5, 'Dog', True]

In [11]:
new_array = np.array(l)
print(new_array)   #all are converted to string

['1' '2.5' 'Dog' 'True']


In [13]:
for i in new_array:  #checking the type, which is string
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [20]:
b = np.array([1.,2,"3"])
b

array(['1.0', '2', '3'], dtype='<U32')

In [21]:
type(b)

numpy.ndarray

In [22]:
b.dtype #can check single datatype of all elements

dtype('<U32')

## 1.2 numpy array( element wise operations / vectorisation)

In [23]:
import numpy as np

In [25]:
np.arange(1,11) #create ndarray from 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,11,2) #every second no. from 1 to 10

array([1, 3, 5, 7, 9])

### differences b/w lists and ndarrays

In [29]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [30]:
l*2  #not an element wise operation

[1, 2, 3, 4, 1, 2, 3, 4]

In [32]:
l1 = []  #element wise operation requires alot of code
for i in l:
    l1.append(i*2)
l1

[2, 4, 6, 8]

In [33]:
l+2 #not an element wise operation and doesn't work at all :(

TypeError: can only concatenate list (not "int") to list

In [34]:
a = np.arange(1,5) #create ndarray with elements as 1-4
a

array([1, 2, 3, 4])

In [37]:
print(a*2, a+2, a/2, a-2, a**2, 2**a, sep = "\n")  #element wise operations are possible and easy

[2 4 6 8]
[3 4 5 6]
[0.5 1.  1.5 2. ]
[-1  0  1  2]
[ 1  4  9 16]
[ 2  4  8 16]


In [39]:
np.sqrt(a)  #srqt of all elements

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [40]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [41]:
np.sum(a)

10

In [45]:
a.sum()

10

In [46]:
sum(a)

10

In [48]:
a.size #no. of elements in ndarray

4

In [49]:
len(a)  #same as size

4

In [52]:
a[1] = 34.5

In [54]:
np.abs(a) #absolute values of all elements

array([ 1, 34,  3,  4])

In [56]:
np.ceil(a) #rounding up element wise

array([ 1., 34.,  3.,  4.])

In [57]:
l  = [1.2,3,4]

In [58]:
list.ceil(l)

AttributeError: type object 'list' has no attribute 'ceil'

In [68]:
np.around(([2.33]), decimals = 1)  # rounds to given decimal points

array([2.3])

## 1.3 numpy array (indexing and slicing)

In [69]:
import numpy as np

In [70]:
a = np.arange(1,11)  #array from 1 to 10 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
a[0]

1

In [72]:
a[-1]

10

In [73]:
list(enumerate(a))

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [74]:
a[2:6]

array([3, 4, 5, 6])

In [75]:
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a[:5]

array([1, 2, 3, 4, 5])

In [77]:
a[::2]

array([1, 3, 5, 7, 9])

In [78]:
a[::3]

array([ 1,  4,  7, 10])

In [80]:
a[0] = 100 #assignment using index value
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [82]:
a[2:5] = 50 #broadcasting
a

array([100,   2,  50,  50,  50,   6,   7,   8,   9,  10])

In [86]:
a[2:5] = [34,56,78] #this is also possible
a

array([100,   2,  34,  56,  78,   6,   7,   8,   9,  10])

In [87]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
b = a[2:8] #slicing a and assigning it to b
b

array([3, 4, 5, 6, 7, 8])

In [92]:
b[0] = 100 #changing value in b reflects in a as well
b

array([100,   4,   5,   6,   7,   8])

In [94]:
a  #respective element is changed in a as well (referecncing)

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

### making another array from sliced array references to the original while in lists it ref. to a copy

----------------------------------------------------------

## 1.4 numpy array (shape and multiple dimensions